name: Email Step Demo

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f2004618@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo-deps
          key: cache-452ead1

      - name: prime-cache-452ead1
        run: |
          echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
